version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  ApplicationStop:
    - location: install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: install.sh
      timeout: 180
      runas: root


      
